---
- name: include vars
  include_vars: common.yml

- name: install packages
  become: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - nginx
    - gunicorn
    - build-essential
    - python-dev
    - python-pip
    - libffi-dev

- name: install pip modules
  become: yes
  pip:
    requirements: /home/{{ user }}/CTFd/requirements.txt

- name: pull ctfd
  git: repo=https://github.com/isislab/CTFd.git dest=~/CTFd force=yes
  register: ctfd_pulled

- name: make gunicorn dir
  become: yes
  file: path=/etc/gunicorn.d state=directory

- name: copy gunicorn conf
  become: yes
  template:
    src: files/ctfd_gunicorn.conf.j2
    dest: /etc/gunicorn.d/ctfd
    owner: root
    group: root
    mode: 0644
  notify:
      - restart gunicorn

- name: remove default nginx config
  become: yes
  file: path=/etc/nginx/site-enabled/default state=absent

- name: write the ctfd nginx config file
  become: yes
  template:
    src: files/ctfd_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/ctfd
    owner: root
    group: root
    mode: 0644
  notify:
      - restart nginx

- name: ensure gunicorn is running and enabled
  service: name=gunicorn state=started enabled=yes

- name: ensure nginx is running and enabled
  service: name=nginx state=started enabled=yes
