---
- name: install packages
  become: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - nginx
    - gunicorn

- name: pull ctfd
  git: repo=https://github.com/isislab/CTFd.git dest=~/CTFd force=yes
  register: ctfd_pulled

- name: run prepare.sh
  shell: ~/CTFd/prepare.sh
  register: prepareoutput
  when: ctfd_pulled|success

- name: copy gunicorn conf
  become: yes
  copy: src=ctfd_gunicorn.conf dest=/etc/gunicorn.d/ctfd force=yes

- name: write the nginx config file
  become: yes
  copy: src=ctfd_nginx.conf dest=/etc/nginx/sites-enabled/ctfd force=yes
  notify:
      - restart nginx

- name: ensure nginx is running and enabled
  service: name=nginx state=started enabled=yes
