---
- name: include vars
  include_vars: common.yml

- name: install packages
  become: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - nginx
    - gunicorn
    - build-essential
    - python-dev
    - python-pip
    - libffi-dev

- name: pull ctfd
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/isislab/CTFd.git dest=~/CTFd force=yes
  register: ctfd_pulled

- name: install pip modules
  become: yes
  when: ctfd_pulled|success
  pip:
    requirements: /home/{{ user }}/CTFd/requirements.txt

- name: make gunicorn dir
  become: yes
  file: path=/etc/gunicorn.d state=directory

- name: copy gunicorn conf
  become: yes
  template:
    src: files/ctfd_gunicorn.conf.j2
    dest: /etc/gunicorn.d/ctfd
    owner: root
    group: root
    mode: 0644
  notify:
      - restart gunicorn

- name: remove default nginx config
  become: yes
  file: path=/etc/nginx/site-enabled/default state=absent

- name: copy dhparam
  become: yes
  copy:
    src: files/dhparam.pem
    dest: /etc/ssl/certs/
    owner: root
    group: root
    mode: 0644

- name: write the ctfd nginx config file
  become: yes
  template:
    src: files/ctfd_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/ctfd
    owner: root
    group: root
    mode: 0644
  notify:
      - restart nginx

- name: copy the ctfd.db
  become: yes
  copy:
    src: files/ctfd.db
    dest: /home/{{ user }}/CTFd/CTFd/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  notify:
      - restart nginx
      - restart gunicorn

- name: ensure web services are running and enabled
  service: name={{ item }} state=started enabled=yes
  with_items: [nginx, gunicorn]
